
# <http://Tomassetti.me/continous-integration-on-linux-and-windows-travis-and-appveyor/>
# <http://GitHub.com/pypa/setuptools/blob/master/appveyor.yml>

environment:

  APPVEYOR: True
# CODECOV_ENV: APPVEYOR_JOB_NAME

  matrix:
    # <http://www.AppVeyor.com/docs/windows-images-software/#python>
    - APPVEYOR_JOB_NAME: "Python27-64bit"
      PYTHON: "C:\\Python27-x64"
    - APPVEYOR_JOB_NAME: "Python27-32bit"
      PYTHON: "C:\\Python27"
    # Python-26 no longer supported

    - APPVEYOR_JOB_NAME: "Python39-64bit"
      PYTHON: "C:\\Python39-x64"
    - APPVEYOR_JOB_NAME: "Python39-64bit-isLazy-0"
      PYTHON: "C:\\Python39-x64"
      PYTHONDONTWRITEBYTECODE: "1"
      PYGEODESY_LAZY_IMPORT: "0"
    - APPVEYOR_JOB_NAME: "Python39-32bit"
      PYTHON: "C:\\Python39"
    - APPVEYOR_JOB_NAME: "Python39-32bit-isLazy-0"
      PYTHON: "C:\\Python39"
      PYTHONDONTWRITEBYTECODE: "1"
      PYGEODESY_LAZY_IMPORT: "0"

    - APPVEYOR_JOB_NAME: "Python38-64bit"
      PYTHON: "C:\\Python38-x64"
    - APPVEYOR_JOB_NAME: "Python38-64bit-isLazy-0"
      PYTHON: "C:\\Python38-x64"
      PYTHONDONTWRITEBYTECODE: "1"
      PYGEODESY_LAZY_IMPORT: "0"
    - APPVEYOR_JOB_NAME: "Python38-32bit"
      PYTHON: "C:\\Python38"
    - APPVEYOR_JOB_NAME: "Python38-32bit-isLazy-0"
      PYTHON: "C:\\Python38"
      PYTHONDONTWRITEBYTECODE: "1"
      PYGEODESY_LAZY_IMPORT: "0"

    - APPVEYOR_JOB_NAME: "Python37-64bit"
      PYTHON: "C:\\Python37-x64"
    - APPVEYOR_JOB_NAME: "Python37-64bit-isLazy-0"
      PYTHON: "C:\\Python37-x64"
      PYTHONDONTWRITEBYTECODE: "1"
      PYGEODESY_LAZY_IMPORT: "0"
    - APPVEYOR_JOB_NAME: "Python37-32bit"
      PYTHON: "C:\\Python37"
    - APPVEYOR_JOB_NAME: "Python37-32bit-isLazy-0"
      PYTHON: "C:\\Python37"
      PYTHONDONTWRITEBYTECODE: "1"
      PYGEODESY_LAZY_IMPORT: "0"

    # - APPVEYOR_JOB_NAME: "Python36-64bit"
    #   PYTHON: "C:\\Python36-x64"
    # - APPVEYOR_JOB_NAME: "Python36-32bit"
    #   PYTHON: "C:\\Python36"

install:
  # symlink python from a directory with a space
  - "mklink /d \"C:\\Program Files\\Python\" %PYTHON%"
  - "set PYTHON=\"C:\\Program Files\\Python\""
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  # UTF-8 for unicode test results
  - set PYTHONIOENCODING=utf-8
  - python -m pip install --upgrade pip
  - pip install geographiclib
  # pip install win_unicode_console

build: off

#cache:
#  - '%LOCALAPPDATA%\pip\Cache'

test_script:
  - cd C:\\projects\\pygeodesy
  - python test\\run.py -failedonly
  # python test\\run.py -results
  # type testresults\\testresults*Windows*.txt

# version: '{build}'
