language: python

python:
# - "2.6"
  - "2.7"
# - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "pypy"
  - "pypy3"

cache: pip

install:
  - pip install --upgrade pip
  - pip install distro
  - pip install geographiclib

script:
  - python -c 'import distro; print(distro.id(), repr(distro.name()))'
  - python -c 'import platform; print(platform.uname(), platform.dist())'
  - python -c 'import geographiclib; print("geographiclib " + geographiclib.__version__)'
  - python test/run.py -failedonly
